name: Build and Test PogRust Development Image

on:
  schedule:
    - cron: "20 04 * * *"
  push:
    branches: ["dev"]
    paths: ["pogrust/**", ".github/workflows/dev-pogrust-build.yml"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["dev"]
    paths: ["pogrust/**", ".github/workflows/dev-pogrust-build.yml"]
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push-pogrust
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./pogrust
